backend:
  name: git-gateway
  branch: main

media_folder: "site/static/img" # Global media folder for all uploads
public_folder: "/img" # Global public folder for all uploaded media

local_backend: true

collections:
  - name: "homepage"
    label: "Homepage"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        media_folder: "/../../static/img/homepage"
        public_folder: "/img/homepage"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Text Color", name: "textcolor", widget: "color"}
          - {label: "Background Color", name: "backgroundcolor", widget: "color"}
          - label: "Menu Items"
            name: "menu_items"
            widget: "list"
            fields:
              - {label: "Heading", name: "heading", widget: "string"}
              - {label: "Image", name: "image", widget: "image"}

  - name: "fables"
    label: "Fables"
    folder: "site/content/fables"
    create: true
    slug: "{{slug}}"
    media_folder: "/../../static/img/fables" # Relative to the content folder
    public_folder: "/img/fables"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Year", name: "year", widget: "number"}
      - {label: "Dimensions", name: "dimensions", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "ikons"
    label: "Ikons"
    folder: "site/content/ikons"
    create: true
    slug: "{{slug}}"
    media_folder: "/../../static/img/ikons" # Relative to the content folder
    public_folder: "/img/ikons"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Year", name: "year", widget: "number"}
      - {label: "Dimensions", name: "dimensions", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "untitled"
    label: "Untitled"
    folder: "site/content/untitled"
    create: true
    slug: "{{slug}}"
    media_folder: "/../../static/img/untitled" # Relative to the content folder
    public_folder: "/img/untitled"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Year", name: "year", widget: "number"}
      - {label: "Dimensions", name: "dimensions", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "collections"
    label: "Collections"
    folder: "site/content/collections"
    create: true
    slug: "{{slug}}"
    media_folder: "/../../static/img/collections" # Relative to the content folder
    public_folder: "/img/collections"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Year", name: "year", widget: "number"}
      - {label: "Dimensions", name: "dimensions", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "miscellaneous"
    label: "Miscellaneous"
    folder: "site/content/miscellaneous"
    create: true
    slug: "{{slug}}"
    media_folder: "/../../static/img/miscellaneous" # Relative to the content folder
    public_folder: "/img/miscellaneous"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Year", name: "year", widget: "number"}
      - {label: "Dimensions", name: "dimensions", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "biography"
    label: "Biography"
    folder: "site/content/biography"
    create: true
    slug: "{{slug}}"
    media_folder: "/../../static/img/biography" # Relative to the content folder
    public_folder: "/img/biography"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Year", name: "year", widget: "number"}
      - {label: "Dimensions", name: "dimensions", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
